'use client';
// Displays a UPI QR code generated by the backend (via Razorpay)
// Auto-polls payment status every 3s and calls onSuccess when confirmed

import { useEffect, useRef } from 'react';

interface Props {
  qrImageUrl: string;
  paymentId: string;
  onSuccess: () => void;
  onExpire: () => void;
}

export default function UpiQrCode({ qrImageUrl, paymentId, onSuccess, onExpire }: Props) {
  const timer = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    timer.current = setInterval(async () => {
      const res  = await fetch(`/api/upi/status?paymentId=${paymentId}`);
      const data = await res.json();
      if (data.status === 'captured') { clearInterval(timer.current!); onSuccess(); }
      if (data.status === 'expired')  { clearInterval(timer.current!); onExpire();  }
    }, 3000);
    return () => clearInterval(timer.current!);
  }, [paymentId, onSuccess, onExpire]);

  return (
    <div className="flex flex-col items-center gap-3 p-4 border rounded-2xl">
      <p className="text-sm text-gray-500">Scan with any UPI app</p>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={qrImageUrl} alt="UPI QR Code" className="w-52 h-52" />
      <p className="text-xs text-gray-400 animate-pulse">Waiting for payment…</p>
    </div>
  );
}
